name: Snapit

on:
  issue_comment:
    types:
      - created

env:
  PNPM_VERSION: '8.7.0'

jobs:
  snapit:
    name: Snapit
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/snapit' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
      - name: Setup deps
        uses: ./.github/actions/setup-cli-deps
        with:
          node-version: 22.2.0
      - name: Force snapshot changeset
        run: "mv .changeset/force-snapshot-build.md.ignore .changeset/force-snapshot-build.md"
      - name: Create snapshot version
        uses: Shopify/snapit@f9e1c0990888000fb4b2e622319ee69e2dc84e67 # pin@main
        with:
          global_install: 'true'
          github_comment_included_packages: '@shopify/cli'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
